### ISSUE TITLE
post share has to be pressed twice on android

### ISSUE THREAD

**Issue by vujevits** [agazso/postmodern#147]
**Describe the bug**
To share a post, the share button has to be pressed twice.

**To Reproduce**
1. Long press post to show share button
2. Tap on share - spinner appears, but changes back to empty share button
3. Tap on share again - spinner appears, changes to filled share button

**Expected behavior**
1. Long press post to show share button
2. Tap on share again - spinner appears, changes to filled share button

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Vodafone Android
 - OS: 8.1.0
 - Version 0.9.28

Also on iOS simulator

**Comment by agazso** [comment]
I am afraid that this is not an android bug, but rather a Swarm gateway issue. If the upload is not finished before a certain timeout then the gateway returns 500. This does not necessary mean that the upload was failed, it's even possible that it succeeded but the info has not yet propagated on the network.

Then when you try again it will return as soon as you finished uploading your post, because by that time the data is already on the network. This will be fixed somewhat when we will use lightnode, because then it will return as soon as the data is uploaded to the lightnode. This will work when you are offline, but it won't mean that others will be able to see your update as soon as the indicator is finished, so we may have to double check somehow (from the public gateway maybe?) when we can report back it's finished.

**Comment by vujevits** [comment]
I'm suspicious about this too, btw I just tried it in the iOS simulator and had to press it 5 times. The interesting part is, that when it's finally successful, the spinner have had rotated longer then in the previous attempts.

**Comment by vujevits** [comment]
this is related to #66 , closing issue
